# This file was orinally generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded
# and modified for Arducleo Samples
# 
# .nfc, 2016/07/30 18:30:05

PLAT_MCU=f051k8
SYS_OBJ_DIR = ../../../mbed/TARGET_ARDUCLEO_F051K8/TOOLCHAIN_GCC_ARM/
SYS_OBJECTS = $(wildcard $(SYS_OBJ_DIR)*.o)


INCLUDE_PATHS = -I../. -I../../ -I../../../mbed -I../../../mbed/TARGET_ARDUCLEO_F051K8 -I../../../mbed/TARGET_ARDUCLEO_F051K8/TARGET_STM -I../../../mbed/TARGET_ARDUCLEO_F051K8/TARGET_STM/TARGET_STM32F0 -I../../../mbed/TARGET_ARDUCLEO_F051K8/TARGET_STM/TARGET_STM32F0/TARGET_ARDUCLEO_F051K8 -I../../../mbed/TARGET_ARDUCLEO_F051K8/TOOLCHAIN_GCC_ARM 
LIBRARY_PATHS = -L../../../mbed/TARGET_ARDUCLEO_F051K8/TOOLCHAIN_GCC_ARM 
LIBRARIES = -lmbed 
LINKER_SCRIPT = ../../../mbed/TARGET_ARDUCLEO_F051K8/TOOLCHAIN_GCC_ARM/STM32F0xx.ld

CPU = -mcpu=cortex-m0 -mthumb 
CC_FLAGS = -c -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -fno-builtin -ffunction-sections -fdata-sections -funsigned-char -MMD -fno-delete-null-pointer-checks -fomit-frame-pointer -mcpu=cortex-m0 -mthumb -Os -std=gnu99 -include mbed_config.h -MMD -MP
CPPC_FLAGS = -c -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -fno-builtin -ffunction-sections -fdata-sections -funsigned-char -MMD -fno-delete-null-pointer-checks -fomit-frame-pointer -mcpu=cortex-m0 -mthumb -Os -std=gnu++98 -fno-rtti -Wvla -include mbed_config.h -MMD -MP
ASM_FLAGS = -x assembler-with-cpp -c -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -fno-builtin -ffunction-sections -fdata-sections -funsigned-char -MMD -fno-delete-null-pointer-checks -fomit-frame-pointer -mcpu=cortex-m0 -mthumb -Os
CC_SYMBOLS = -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -DTARGET_LIKE_MBED -DDEVICE_PORTINOUT=1 -D__MBED_CMSIS_RTOS_CM -DTARGET_STM32F0 -DDEVICE_RTC=1 -DTOOLCHAIN_object -D__CMSIS_RTOS -DTARGET_ARDUCLEO_F051K8 -DTOOLCHAIN_GCC -DDEVICE_CAN=0 -DTARGET_CORTEX_M -DARM_MATH_CM0 -DDEVICE_ANALOGOUT=1 -DTARGET_UVISOR_UNSUPPORTED -DTARGET_M0 -DDEVICE_PWMOUT=1 -DTARGET_ARDUCLEO_F051K8 -DDEVICE_INTERRUPTIN=1 -D__CORTEX_M0 -DDEVICE_I2C=1 -DDEVICE_PORTOUT=1 -DDEVICE_STDIO_MESSAGES=1 -DTARGET_FF_MORPHO -DDEVICE_LOWPOWERTIMER=1 -DTARGET_FF_ARDUINO -DTARGET_RELEASE -DTARGET_STM -DMBED_BUILD_TIMESTAMP=1471926870.02 -DDEVICE_PORTIN=1 -DDEVICE_SLEEP=1 -DTOOLCHAIN_GCC_ARM -DDEVICE_SPI=1 -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 -DDEVICE_SERIAL=1 -DTARGET_LIKE_CORTEX_M0 

# -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -u _printf_float
LD_FLAGS =-Wl,--gc-sections -Wl,--wrap,main -mcpu=cortex-m0 -mthumb --specs=nano.specs 
LD_SYS_LIBS = -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys
