//
// generated by cardpad
//

// xml ui resource
char *calc_ui = [[
<?xml version="1.0" ?>
<ControlWnd Name="Calculator For Javacard" LocationX="0" LocationY="0" SizeWidth="317" SizeHeight="394" >
  <ControlGroups>
    <ControlGroup Name="Group 1">
      <Controls>

        <TextBox Name="txtDisp" Visible="true" Enabled="true"
            LocationX="16" LocationY="10" SizeWidth="262" SizeHeight="32"
            Text="--- No Card ---"></TextBox> 

        <Button Name="btnClear" Visible="true" Enabled="true"
            LocationX="225" LocationY="49" SizeWidth="53" SizeHeight="57"
            Text="C"></Button> 

        <Button Name="btn7" Visible="true" Enabled="true"
            LocationX="17" LocationY="106" SizeWidth="53" SizeHeight="57"
            Text="7"></Button> 

        <Button Name="btn8" Visible="true" Enabled="true"
            LocationX="69" LocationY="106" SizeWidth="53" SizeHeight="57"
            Text="8"></Button> 

        <Button Name="btn9" Visible="true" Enabled="true"
            LocationX="121" LocationY="106" SizeWidth="53" SizeHeight="57"
            Text="9"></Button> 

        <Button Name="btnDiv" Visible="true" Enabled="true"
            LocationX="173" LocationY="106" SizeWidth="53" SizeHeight="57"
            Text="/"></Button> 

        <Button Name="btnST" Visible="true" Enabled="true"
            LocationX="225" LocationY="106" SizeWidth="53" SizeHeight="57"
            Text="ST"></Button> 

        <Button Name="btn4" Visible="true" Enabled="true"
            LocationX="17" LocationY="162" SizeWidth="53" SizeHeight="57"
            Text="4"></Button> 

        <Button Name="btn5" Visible="true" Enabled="true"
            LocationX="69" LocationY="162" SizeWidth="53" SizeHeight="57"
            Text="5"></Button> 

        <Button Name="btn6" Visible="true" Enabled="true"
            LocationX="121" LocationY="162" SizeWidth="53" SizeHeight="57"
            Text="6"></Button> 

        <Button Name="btnMul" Visible="true" Enabled="true"
            LocationX="173" LocationY="162" SizeWidth="53" SizeHeight="57"
            Text="*"></Button> 

        <Button Name="btnRM" Visible="true" Enabled="true"
            LocationX="225" LocationY="162" SizeWidth="53" SizeHeight="57"
            Text="RM"></Button> 

        <Button Name="btn1" Visible="true" Enabled="true"
            LocationX="17" LocationY="218" SizeWidth="53" SizeHeight="57"
            Text="1"></Button> 

        <Button Name="btn2" Visible="true" Enabled="true"
            LocationX="69" LocationY="218" SizeWidth="53" SizeHeight="57"
            Text="2"></Button> 

        <Button Name="btn3" Visible="true" Enabled="true"
            LocationX="121" LocationY="218" SizeWidth="53" SizeHeight="57"
            Text="3"></Button> 

        <Button Name="btnSUB" Visible="true" Enabled="true"
            LocationX="173" LocationY="218" SizeWidth="53" SizeHeight="57"
            Text="-"></Button> 

        <Button Name="btnMM" Visible="true" Enabled="true"
            LocationX="225" LocationY="218" SizeWidth="53" SizeHeight="57"
            Text="M+"></Button> 

        <Button Name="btn0" Visible="true" Enabled="true"
            LocationX="17" LocationY="274" SizeWidth="53" SizeHeight="57"
            Text="0"></Button> 

        <Button Name="btnAdd" Visible="true" Enabled="true"
            LocationX="173" LocationY="274" SizeWidth="53" SizeHeight="57"
            Text="+"></Button> 

        <Button Name="btnEQ" Visible="true" Enabled="true"
            LocationX="225" LocationY="274" SizeWidth="53" SizeHeight="57"
            Text="="></Button> 

        <Button Name="btnInst" Visible="true" Enabled="true"
            LocationX="69" LocationY="274" SizeWidth="53" SizeHeight="57"
            Text="Inst"></Button> 

        <Button Name="btnDel" Visible="true" Enabled="true"
            LocationX="121" LocationY="274" SizeWidth="53" SizeHeight="57"
            Text="Del"></Button> 

        <Button Name="btnReset" Visible="true" Enabled="true"
            LocationX="17" LocationY="53" SizeWidth="53" SizeHeight="49"
            Text="RST"></Button> 

        <Button Name="btnOn" Visible="true" Enabled="true"
            LocationX="69" LocationY="53" SizeWidth="53" SizeHeight="49"
            Text="On"></Button> 
            
      </Controls>
    </ControlGroup>
  </ControlGroups>
</ControlWnd>
]];

/* --------------------------------------------- end-of-script ---------------*/
